### ISSUE TITLE
Typescript rewrite

### ISSUE THREAD

**Issue by jsbrain** [jimenezmaximiliano/very-simple-queue#12]
Hey man!
You lib looks very cool, love the api.

If you would write it in typescript that would be just amazing!

Have you already considered doing so?

**Comment by jsbrain** [comment]
Sorry, I just realize you have support already. My bad :D

**Comment by jimenezmaximiliano** [comment]
Thanks!

**Comment by jsbrain** [comment]
> Sorry, I just realize you have support already. My bad :D

Nope, I was wrong. Did you consider TypeScript?

**Comment by jimenezmaximiliano** [comment]
I won't rewrite in Typescript but maybe there's a way to add support without needing to rewrite it. You are welcome to submit an MR for that if you like.
