### ISSUE TITLE
[QUESTION] What does the reserved_at field mean?

### ISSUE THREAD

**Issue by horaciogiovine** [jimenezmaximiliano/very-simple-queue#134]
I encountered a scenario where this field has a date in the past and I cant manage to find a way to process it again.
I see its being set on #reserveJob but I dont understand the logic for it.
How can I reschedule a job that already has a reserved_at date but its in the past?
Im thinking about removing this code in `reserveJob`
```
if (!rawJob) {
          await this.#run('COMMIT', []);
          return null;
        }
```

Thank you for the help, great lib!

**Comment by jimenezmaximiliano** [comment]
Hi @horaciogiovine 👋 reserved_at is set when a worker picks up the job. Once it's set, other workers can't pick it up. That way we prevent multiple workers processing the same job at the same time (like a mutex). 
If the job is handled successfully, the job is deleted. If it failed, it's marked as failed.
If the job is not marked as failed, that means that the worker suddenly died, and didn't complete handling the job (or that it's still processing it). For that case, you could set reserved_at to null, and it should be picked up again. This shouldn't normally happen though.

**Comment by horaciogiovine** [comment]
Thanks for answering, yeah, during testing im starting and stopping the server, so the task may have never been processes correctly. 
This could be solved if I implement a method to clear this field for a given job right?

**Comment by jimenezmaximiliano** [comment]
What do you think of doing something similar to handleFailedJob https://github.com/jimenezmaximiliano/very-simple-queue/blob/71bbf0eb64de819e7f7e64ec2464e04555b09ee9/src/QueueClient.js#L121
I think it's almost the same scenario, except that it's not a failed job but a dangling job.

The other issue that your usage is pointing to, is that this library doesn't provide a way to handle graceful shutdowns. If it could handle graceful shutdowns, you probably wouldn't have this issue.

**Comment by horaciogiovine** [comment]
yes, thanks. Im gonna do something similar to that method, remove the reserved date and schedule the job again, to handle cases like this.
Im also gonna implement a way to remove jobs from the queue. 
Other than these edge cases its pretty neat, and the only queue to handle mysql. Thank you

**Comment by horaciogiovine** [comment]
@jimenezmaximiliano that sounds very helpful, im gonna update my code to use this, thanks for the tip!

**Comment by jimenezmaximiliano** [comment]
No worries. I'll close this issue then. Feel free to create another one (if this one can't be re-opened) if you have any more questions.
